default:
    image: node:latest
    variables:
        CI: 1
        NO_SANDBOX: 1
    before_script:
        - npm install -g codacy-coverage

        - apt-get update
        - apt-get install -y wget gnupg
        - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
        - sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
        - apt-get update
        - apt-get install -y google-chrome-unstable fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst fonts-freefont-ttf --no-install-recommends
        - apt-get install -y xvfb
        - rm -rf /var/lib/apt/lists/*
    script:
        - npm install
        - npm run build -- --noEmit
        - xvfb-run --server-args="-screen 0 1024x768x24" npm run test:ci
    after_script:
        - cat ./coverage/lcov.info | codacy-coverage --language=typescript;
    artifacts:
        paths:
            - instamancer_tests.log
        expire_in: 1 week